//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_console_ef_modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StuRoll { get; set; }
        public string StudentName { get; set; }
        public int CollegeCollegeid { get; set; }
    
        public virtual College College { get; set; }
    }
}
